dados = read.csv("dados - respostas formulário.csv", header=T, sep=";")
attach(dados)
prop.table(table(ingresso))
prop.table(table(sexo))
prop.table(table(grupo_sanguineo))
prop.table(table(ingresso))
prop.table(table(ingere_pao))
prop.table(table(ingere_massa))
prop.table(table(ingere_refri))
prop.table(table(ingere_alcool))
prop.table(table(fruta_gosta))

summary(idade)
sd(idade)
summary(peso)
sd(peso)
summary(n_refeicoes_dia)
sd(n_refeicoes_dia)
